id: genomics-reporting
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 2
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: cg
canonical: http://hl7.org/fhir/uv/genomics-reporting
packageId: hl7.fhir.uv.genomics-reporting
version: 4.0.0-cibuild
name: GenomicsReporting
title: Genomics Reporting Implementation Guide
status: active
publisher:
  name: HL7 International / Clinical Genomics
  url: http://www.hl7.org/Special/committees/clingenomics
  email: cg@lists.HL7.org
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World"
description: Guidelines for reporting of clinical genomics results using HL7 FHIR.
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-version: true
  shownav: 'true'
  special-url:
    - http://terminology.hl7.org/CodeSystem/sequence-phase-relationship-cs
    - http://terminology.hl7.org/CodeSystem/variant-confidence-status-cs
    - https://www.ncbi.nlm.nih.gov/gtr
  pin-canonicals: pin-multiples
copyrightYear: 2025+
releaseLabel: CI Build

pages:
  index.html:
    title: Home Page
    generation: markdown
  background.html:
    title: Genomic Background
    generation: markdown
  general.html:
    title: General Genomic Reporting
    generation: markdown
  sequencing.html:
    title: Variant Reporting
    generation: markdown
  cytogenomics.html:
    title: Cytogenomic Reporting
    generation: markdown
  pharmacogenomics.html:
    title: Pharmacogenomic Reporting
    generation: markdown
  somatics.html:
    title: Somatic Reporting
    generation: markdown
  histocompatibility.html:
    title: Histocompatibility and Immunogenetic Reporting
    generation: markdown
  operations.html:
    title: Genomic Operations
    generation: markdown
  downloads.html:
    title: Useful Downloads
    generation: markdown
  v2.html:
    title: "Appendix A: Relation to v2 reporting"
    generation: markdown
  cgapps.html:
    title: "Appendix B: Clinical Genomic Apps"
    generation: markdown
  domain.html:
    title: "Appendix C: HL7 Domain Analysis Model"
    generation: markdown
  usecases.html:
    title: "Appendix D: Query Guidance"
    generation: markdown
  codings.html:
    title: "Appendix E: External Coding Systems"
    generation: markdown
  conversion.html:
    title: "Appendix F: Conversion from FHIR Core STU3"
    generation: markdown
  molecularsequence.html:
    title: "Appendix G: Molecular Sequence"
    generation: markdown
  groupingguidance.html:
    title: "Appendix H: Grouping Guidance"
    generation: markdown
  glossary.html:
    title: "Appendix I: Glossary"
    generation: markdown
  changes.html:
    title: "Change Log"
    generation: markdown
  artifacts.html:
    title: Artifact List
    generation: markdown
